CREATE TABLE person
(
    person_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(100) NOT NULL UNIQUE,
    year      INT          NOT NULL
);

CREATE TABLE book
(
    book_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title     VARCHAR NOT NULL,
    author    VARCHAR NOT NULL,
    year      INT     NOT NULL,
    person_id INT     REFERENCES person (person_id) ON DELETE SET NULL,
    assigned_from TIMESTAMP
);